---
- name: initial configuration
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Show Running
      ios_command:
        commands:
          - show run
          - show ip route
      register: config

    - name: Save Config to Local File
      copy:
        content: "{{ config.stdout | replace('\\n','\n') }}"
        dest: "show-output/{{ inventory_hostname }}.ios"
        
...
